### ISSUE TITLE
Cannot read property 'nodeName' of null

### ISSUE THREAD

**Issue by flfruitios** [najeeb-rifaat/react-native-ci-tools#13]
When I tried entering: 
react-native-ci-tools bundle "com.foo.react" "Foo React" -i

TypeError: Cannot read property 'nodeName' of null
TypeError: Cannot read property 'nodeName' of null
TypeError: Cannot read property 'nodeName' of null
    at Object.parse (/usr/local/lib/node_modules/react-native-ci-tools/node_modules/plist/lib/parse.js:69:25)
    at Promise (/usr/local/lib/node_modules/react-native-ci-tools/src/utils/plist_parse.js:12:28)
    at new Promise (<anonymous>)
    at Object.module.exports [as plistParse] (/usr/local/lib/node_modules/react-native-ci-tools/src/utils/plist_parse.js:6:38)
    at Promise.all.fileObjList.map.thisFileObj (/usr/local/lib/node_modules/react-native-ci-tools/src/bundle/ios/plist.js:17:78)
    at Array.map (<anonymous>)
    at strategy.utils.globSearch.then.then.then.fileObjList (/usr/local/lib/node_modules/react-native-ci-tools/src/bundle/ios/plist.js:17:44)
    at <anonymous>

**Comment by mapokapo** [comment]
I'm getting the same error

**Comment by DChiuch** [comment]
I got around this by deleting my ios/Pods folder before using react-native-ci-tools.

**Comment by lanedirt** [comment]
Thanks @DChiuch, deleting the ios/Pods folder before running the command solved my problem as well!
